from . import pricing_scale
from . import res_partner
from . import shipment
from . import shipment_line
from . import shipment_vehicle
from . import shipment_vehicle_category
from . import postal_code
from . import sale_order
from . import sale_order_line
